version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: chessDRA2021
      MYSQL_USER: user
      MYSQL_PASSWORD: chessDRA21
      MYSQL_DATABASE: chessDB

  adminer:
      depends_on:
        - db
      image: adminer
      restart: unless-stopped
      ports:
        - 8080:8080

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
          - "/etc/localtime:/etc/localtime:ro"
          - "/etc/timezone:/etc/timezone:ro"
          - "mosquitto-config:/opt/mosquitto/config"
          - "mosquitto-data:/opt/mosquitto/data"
          - "mosquitto-log:/opt/mosquitto/log"

volumes:
  db_data:
  mosquitto-config:
  mosquitto-data:
  mosquitto-log:


